# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: CszMqIyeNvdwjuMjNUm8zQGPEBNHOnx1
            client-secret: l0U8Fq2ekQTdncIPRdTUeMEndnciiSuZvhZ22GJGd4WKI-dbB0nup6t252h8JmGG
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://demo1task.us.auth0.com/